package io.github.evildarkarchon.jbsa.internal.pack;

import io.github.evildarkarchon.jbsa.FailureKind;
import io.github.evildarkarchon.jbsa.internal.io.IoContext;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.ReadableByteChannel;

/**
 * Bounded 64 KiB window copies between sources, scratch, and staged output. Every caller reserves
 * {@link #WINDOW_BYTES} per live window before calling, so these helpers never allocate unadmitted
 * heap.
 */
final class PayloadWindows {
  /** The size of every transfer, comparison, and replay window. */
  static final int WINDOW_BYTES = 64 * 1024;

  private PayloadWindows() {}

  /** Reads an absolute range into a window; SpillBuffer and StagedFile both fit this shape. */
  @FunctionalInterface
  interface Reader {
    /** Fills the window's remaining bytes from {@code position}. */
    void read(long position, ByteBuffer window) throws IOException;
  }

  /** A positional bounded write destination. */
  @FunctionalInterface
  interface Sink {
    /** Consumes the window's remaining bytes at a position relative to the payload start. */
    void write(long offset, ByteBuffer window) throws IOException;
  }

  /** Observes cancellation between bounded steps. */
  @FunctionalInterface
  interface Checkpoint {
    /** Throws when the operation must stop. */
    void check() throws IOException;
  }

  /**
   * Enforces the declared source length, including a terminal read for excess generated bytes, and
   * bounds stalled channels. One window is live.
   */
  static void transfer(
      ReadableByteChannel input, long length, Sink sink, Checkpoint checkpoint, IoContext context)
      throws IOException {
    if (input == null) throw context.failure(FailureKind.SOURCE, "source.invalid-channel", null);
    ByteBuffer buffer = ByteBuffer.allocate(WINDOW_BYTES);
    long count = 0;
    int idle = 0;
    while (true) {
      checkpoint.check();
      buffer
          .clear()
          .limit((int) Math.min(buffer.capacity(), length - count + (count == length ? 1 : 0)));
      int read = input.read(buffer);
      if (read < 0) break;
      if (read == 0) {
        if (++idle > 16) throw context.failure(FailureKind.SOURCE, "io.no-progress", null);
        continue;
      }
      idle = 0;
      if (read > length - count)
        throw context.failure(FailureKind.SOURCE, "source.length-mismatch", null);
      sink.write(count, buffer.flip());
      count += read;
    }
    if (count != length) throw context.failure(FailureKind.SOURCE, "source.length-mismatch", null);
  }

  /** Confirms a shortlisted candidate with exact bounded reads. Two windows are live. */
  static boolean equal(
      Reader left, long leftStart, Reader right, long rightStart, long size, Checkpoint checkpoint)
      throws IOException {
    ByteBuffer a = ByteBuffer.allocate(WINDOW_BYTES);
    ByteBuffer b = ByteBuffer.allocate(WINDOW_BYTES);
    for (long offset = 0; offset < size; ) {
      checkpoint.check();
      int count = (int) Math.min(a.capacity(), size - offset);
      a.clear().limit(count);
      b.clear().limit(count);
      left.read(leftStart + offset, a);
      right.read(rightStart + offset, b);
      if (!a.flip().equals(b.flip())) return false;
      offset += count;
    }
    return true;
  }

  /**
   * Replays a stabilized range without counting its logical bytes again in progress. One window is
   * live; the sink observes cancellation on every write.
   */
  static void replay(Reader source, long start, long size, Sink sink) throws IOException {
    ByteBuffer bytes = ByteBuffer.allocate(WINDOW_BYTES);
    for (long offset = 0; offset < size; ) {
      int count = (int) Math.min(bytes.capacity(), size - offset);
      bytes.clear().limit(count);
      source.read(start + offset, bytes);
      sink.write(offset, bytes.flip());
      offset += count;
    }
  }
}
