package io.github.evildarkarchon.jbsa.fixtures;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.util.zip.Adler32;

/**
 * Materializes independent TES4 conformance vectors as reviewable hexadecimal text. Generated bytes
 * are CC0-1.0; this implementation is Apache-2.0 and has no product dependency.
 */
public final class BsaCv1FixtureGenerator {
  private static final String REVISION = "fd1e36020b2b5b6217e553dc0038983146a2e2dd";
  private static final String COMMAND =
      "java -cp jbsa-test-support/target/classes "
          + "io.github.evildarkarchon.jbsa.fixtures.BsaCv1FixtureGenerator --output <empty-directory>";

  private BsaCv1FixtureGenerator() {}

  /** Runs deterministic generation into an absent or empty directory; invalid arguments fail. */
  public static void main(String[] args) throws IOException {
    if (args.length != 2 || !args[0].equals("--output"))
      throw new IllegalArgumentException("Expected --output <empty-directory>");
    materialize(Path.of(args[1]));
  }

  /**
   * Writes a complete new corpus, rejecting nonempty destinations to protect accepted evidence.
   * Output archives are lowercase hexadecimal plus LF; decode the text before archive operations.
   */
  public static void materialize(Path root) throws IOException {
    Objects.requireNonNull(root, "root");
    if (Files.exists(root))
      try (var entries = Files.list(root)) {
        if (entries.findAny().isPresent())
          throw new IOException("Fixture destination must be empty");
      }
    Files.createDirectories(root);
    List<Map<String, Object>> records = new ArrayList<>(), recipes = new ArrayList<>();
    for (Vector vector : vectors()) {
      String path = "artifacts/" + vector.id() + ".hex";
      byte[] encoded =
          (HexFormat.of().formatHex(vector.bytes()) + "\n").getBytes(StandardCharsets.US_ASCII);
      Path target = root.resolve(path);
      Files.createDirectories(target.getParent());
      Files.write(target, encoded);
      Map<String, String> options =
          Map.of(
              "representation",
              "lowercase hexadecimal plus LF",
              "wire_sha256",
              sha256(vector.bytes()),
              "wire_size",
              Integer.toString(vector.bytes().length));
      String recipe = "bsa-067-v1|" + vector.id() + "|" + vector.procedure();
      Map<String, Object> record = new LinkedHashMap<>();
      record.put("id", vector.id());
      record.put("kind", vector.kind());
      record.put("coverage", List.of("structural", "bsa-067"));
      record.put("creator", "JBSA project contributors");
      record.put(
          "source",
          "Independently authored from docs/spec/formats/versioned-bsa.md; " + vector.procedure());
      record.put("spdx_license", "CC0-1.0");
      record.put(
          "generation",
          Map.of("procedure", vector.procedure(), "command", COMMAND, "options", options));
      record.put("reference_snapshot_revision", REVISION);
      record.put("oracle_sha256", null);
      record.put("input_sha256", sha256(recipe.getBytes(StandardCharsets.UTF_8)));
      record.put("output", Map.of("path", path, "sha256", sha256(encoded)));
      record.put("redistribution_class", "project-authored-redistributable");
      records.add(record);
      recipes.add(
          Map.of(
              "id",
              vector.id(),
              "kind",
              vector.kind(),
              "coverage",
              List.of("structural", "bsa-067"),
              "input",
              recipe,
              "output_path",
              path,
              "parameters",
              options));
    }
    Map<String, Object> manifest = new LinkedHashMap<>();
    manifest.put("schema_version", 1);
    manifest.put("corpus_id", "jbsa-bsa067-cv1-fixtures-v1");
    manifest.put("generated_on", "2026-09-08");
    manifest.put("reference_snapshot_revision", REVISION);
    manifest.put(
        "generator",
        Map.of(
            "id",
            "jbsa-bsa067-cv1-fixture-generator",
            "version",
            "1",
            "implementation",
            "jbsa-test-support/src/main/java/io/github/evildarkarchon/jbsa/fixtures/BsaCv1FixtureGenerator.java",
            "implementation_spdx_license",
            "Apache-2.0",
            "command",
            COMMAND,
            "options",
            Map.of("output", "<empty-directory>")));
    manifest.put("fixtures", records);
    manifest.put("goldens", List.of());
    Files.writeString(root.resolve("manifest.json"), json(manifest) + "\n", StandardCharsets.UTF_8);
    Files.writeString(
        root.resolve("generator.json"),
        json(
                Map.of(
                    "schema_version",
                    1,
                    "generator_id",
                    "jbsa-bsa067-cv1-fixture-generator",
                    "generator_version",
                    "1",
                    "algorithm",
                    "independent-tes4-wire-recipes-v1",
                    "recipes",
                    recipes))
            + "\n",
        StandardCharsets.UTF_8);
    Files.createDirectories(root.resolve("goldens"));
    Files.writeString(
        root.resolve("goldens/index.json"),
        "{\"schema_version\":1,\"objects\":[]}\n",
        StandardCharsets.UTF_8);
  }

  /**
   * Defines project-owned wire recipes; no product or reference execution supplies expected bytes.
   */
  private static List<Vector> vectors() {
    List<Vector> result = new ArrayList<>();
    for (String mode : List.of("stored", "zlib", "mixed", "raw-deflate", "raw-lz4", "lz4-frame"))
      result.add(
          new Vector(
              "bsa-067-" + mode,
              "generated-archive",
              bsa067(mode),
              "Two meshes entries a.nif=A repeated 1024 times and b.nif=000102ff; codec="
                  + mode
                  + "; RFC1950 literal-only streams"));
    for (String fault :
        List.of(
            "arithmetic-overflow",
            "decompression-mismatch",
            "equal-name-identities",
            "exact-shared-spans",
            "harmless-trailing-bytes",
            "ignorable-constants",
            "illegal-tuples",
            "impossible-counts",
            "missing-name-tables",
            "out-of-range-spans",
            "owning-dispositions",
            "partial-overlap",
            "truncated-spans",
            "undecodable-wire-names",
            "unsafe-absolute-names",
            "unsafe-traversal-names",
            "usable-name-hash-mismatch",
            "windows-invalid-names",
            "unsafe-name-extraction"))
      result.add(
          new Vector(
              "bsa-067-malformed-" + fault,
              "malformed-archive",
              malformed(fault),
              "Apply independent TES4 wire fault recipe "
                  + fault
                  + " to the fixed two-entry corpus"));
    byte[] xml = bsa067("stored", "meshes", List.of("a.xml", "b.nif"), true);
    ByteBuffer.wrap(xml).order(ByteOrder.LITTLE_ENDIAN).putInt(32, 5);
    result.add(
        new Vector(
            "bsa-067-xml",
            "generated-archive",
            xml,
            "Meshes a.xml contributes XML file flag 4 in addition to root-derived mesh flag 1"));
    return result;
  }

  /** Makes each malformed or safely tolerated vector by changing its one declared wire property. */
  private static byte[] malformed(String fault) {
    if (fault.equals("missing-name-tables"))
      return bsa067("stored", "meshes", List.of("a.nif", "b.nif"), false);
    if (fault.equals("unsafe-absolute-names"))
      return bsa067("stored", "c:\\abc", List.of("a.nif", "b.nif"), true);
    if (fault.equals("unsafe-traversal-names") || fault.equals("unsafe-name-extraction"))
      return bsa067("stored", "..\\abc", List.of("a.nif", "b.nif"), true);
    if (fault.equals("windows-invalid-names"))
      return bsa067("stored", "me:hes", List.of("a.nif", "b.nif"), true);
    if (fault.equals("equal-name-identities"))
      return bsa067("stored", "meshes", List.of("a.nif", "a.nif"), true);
    byte[] raw = bsa067(fault.equals("decompression-mismatch") ? "mixed" : "stored");
    ByteBuffer bytes = ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN);
    switch (fault) {
      case "arithmetic-overflow" -> bytes.putInt(8, -16);
      case "decompression-mismatch" -> bytes.putInt(104, 1025);
      case "exact-shared-spans" -> {
        bytes.putInt(84, 1024);
        bytes.putInt(88, 104);
      }
      case "harmless-trailing-bytes" -> {
        byte[] extended = Arrays.copyOf(raw, raw.length + 3);
        extended[raw.length] = (byte) 0xc0;
        extended[raw.length + 1] = (byte) 0xff;
        extended[raw.length + 2] = (byte) 0xee;
        return extended;
      }
      case "ignorable-constants" -> bytes.putInt(12, bytes.getInt(12) | 0x0100);
      case "illegal-tuples" -> bytes.putInt(4, 0x66);
      case "impossible-counts" -> bytes.putInt(20, 3);
      case "out-of-range-spans" -> bytes.putInt(72, raw.length + 1);
      case "owning-dispositions", "usable-name-hash-mismatch" ->
          bytes.putLong(60, bytes.getLong(60) ^ 1);
      case "partial-overlap" -> bytes.putInt(88, 105);
      case "truncated-spans" -> {
        return Arrays.copyOf(raw, raw.length - 1);
      }
      case "undecodable-wire-names" -> raw[92] = (byte) 0x81;
      default -> throw new IllegalArgumentException("Unknown fault recipe " + fault);
    }
    return raw;
  }

  /** Serializes the bounded manifest value model deterministically with sorted object keys. */
  private static String json(Object value) {
    if (value == null) return "null";
    if (value instanceof String string)
      return "\"" + string.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
    if (value instanceof Number || value instanceof Boolean) return value.toString();
    if (value instanceof Map<?, ?> map) {
      List<String> fields = new ArrayList<>();
      map.entrySet().stream()
          .sorted(Comparator.comparing(entry -> entry.getKey().toString()))
          .forEach(
              entry -> fields.add(json(entry.getKey().toString()) + ":" + json(entry.getValue())));
      return "{" + String.join(",", fields) + "}";
    }
    if (value instanceof List<?> list)
      return "[" + String.join(",", list.stream().map(BsaCv1FixtureGenerator::json).toList()) + "]";
    throw new IllegalArgumentException("Unsupported manifest value");
  }

  /** Returns the content address of exact recipe or output bytes. */
  private static String sha256(byte[] bytes) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    } catch (NoSuchAlgorithmException impossible) {
      throw new AssertionError(impossible);
    }
  }

  /** Retains exact generated bytes with their independently declared recipe and provenance kind. */
  private record Vector(String id, String kind, byte[] bytes, String procedure) {}

  /**
   * Serializes the two-entry TES4 recipe directly from fixed wire fields and literal zlib blocks.
   */
  private static byte[] bsa067(String mode) {
    return bsa067(mode, "meshes", List.of("a.nif", "b.nif"), true);
  }

  /**
   * Controls the name tables explicitly so missing-name fixtures remain structurally unambiguous.
   */
  private static byte[] bsa067(
      String mode, String directory, List<String> basenames, boolean named) {
    byte[] folder = directory.getBytes(StandardCharsets.US_ASCII);
    List<byte[]> names =
        basenames.stream().map(name -> name.getBytes(StandardCharsets.US_ASCII)).toList();
    List<byte[]> payloads =
        List.of(
            "A".repeat(1024).getBytes(StandardCharsets.US_ASCII),
            HexFormat.of().parseHex("000102ff"));
    boolean[] compressed = {!mode.equals("stored"), mode.equals("zlib")};
    List<byte[]> framed = new ArrayList<>();
    for (int index = 0; index < payloads.size(); index++) {
      byte[] payload = payloads.get(index);
      if (compressed[index]) {
        byte[] stream = payloadStream(mode, payload);
        framed.add(
            ByteBuffer.allocate(4 + stream.length)
                .order(ByteOrder.LITTLE_ENDIAN)
                .putInt(payload.length)
                .put(stream)
                .array());
      } else framed.add(payload);
    }
    int namesLength = named ? names.stream().mapToInt(name -> name.length + 1).sum() : 0;
    int dataStart = 36 + 16 + (named ? folder.length + 2 : 0) + 32 + namesLength;
    ByteBuffer output =
        ByteBuffer.allocate(dataStart + framed.stream().mapToInt(a -> a.length).sum())
            .order(ByteOrder.LITTLE_ENDIAN);
    int flags = (mode.equals("stored") ? 0x680 : 0x684) | (named ? 3 : 0);
    output
        .putInt(0x00415342)
        .putInt(0x67)
        .putInt(36)
        .putInt(flags)
        .putInt(1)
        .putInt(2)
        .putInt(named ? folder.length + 1 : 0)
        .putInt(namesLength)
        .putInt(1);
    output.putLong(bsaHash(folder, false)).putInt(2).putInt(52 + namesLength);
    if (named) output.put((byte) (folder.length + 1)).put(folder).put((byte) 0);
    int offset = dataStart;
    for (int index = 0; index < names.size(); index++) {
      byte[] content = framed.get(index);
      int toggle = compressed[index] != ((flags & 4) != 0) ? 0x40000000 : 0;
      output
          .putLong(bsaHash(names.get(index), true))
          .putInt(content.length | toggle)
          .putInt(offset);
      offset += content.length;
    }
    if (named) for (byte[] name : names) output.put(name).put((byte) 0);
    for (byte[] content : framed) output.put(content);
    return output.array();
  }

  /**
   * Supplies independently framed codec bytes; unsupported TES4 codecs still have valid stream
   * framing.
   */
  private static byte[] payloadStream(String mode, byte[] payload) {
    byte[] zlib = zlibStoredBlock(payload);
    if (mode.equals("raw-deflate")) return Arrays.copyOfRange(zlib, 2, zlib.length - 4);
    if (mode.equals("raw-lz4")) {
      var output = new java.io.ByteArrayOutputStream();
      output.write(Math.min(15, payload.length) << 4);
      if (payload.length >= 15) {
        int remaining = payload.length - 15;
        while (remaining >= 255) {
          output.write(255);
          remaining -= 255;
        }
        output.write(remaining);
      }
      output.writeBytes(payload);
      return output.toByteArray();
    }
    if (mode.equals("lz4-frame")) {
      // The fixed independent-block descriptor 60 40 has XXH32 header-checksum byte 82.
      return ByteBuffer.allocate(payload.length + 15)
          .order(ByteOrder.LITTLE_ENDIAN)
          .put(HexFormat.of().parseHex("04224d18604082"))
          .putInt(payload.length | 0x80000000)
          .put(payload)
          .putInt(0)
          .array();
    }
    return zlib;
  }

  /** Implements the specification's ASCII BSA component hash without importing product classes. */
  private static long bsaHash(byte[] name, boolean basename) {
    int stemLength = name.length;
    if (basename)
      for (int index = name.length - 1; index >= 0; index--)
        if (name[index] == '.') {
          stemLength = index;
          break;
        }
    if (stemLength == 0) return 0;
    long low =
        Byte.toUnsignedLong(name[stemLength - 1])
            | ((stemLength & 255L) << 16)
            | (Byte.toUnsignedLong(name[0]) << 24);
    if (stemLength > 2) low |= Byte.toUnsignedLong(name[stemLength - 2]) << 8;
    String extension =
        new String(name, stemLength, name.length - stemLength, StandardCharsets.US_ASCII);
    low |=
        switch (extension) {
          case ".kf" -> 0x80;
          case ".nif" -> 0x8000;
          case ".dds" -> 0x8080;
          case ".wav" -> 0x80000000L;
          default -> 0;
        };
    long stemHash = 0, extensionHash = 0;
    for (int index = 1; index < stemLength - 2; index++)
      stemHash = (stemHash * 65599 + Byte.toUnsignedInt(name[index])) & 0xffffffffL;
    for (int index = stemLength; index < name.length; index++)
      extensionHash = (extensionHash * 65599 + Byte.toUnsignedInt(name[index])) & 0xffffffffL;
    return (((stemHash + extensionHash) & 0xffffffffL) << 32) | low;
  }

  /** Frames one tiny payload as an RFC 1950 stream with a final stored DEFLATE block. */
  private static byte[] zlibStoredBlock(byte[] payload) {
    if (payload.length > 0xffff) {
      throw new IllegalArgumentException("Fixture zlib block exceeds its 16-bit stored length");
    }
    ByteBuffer output = ByteBuffer.allocate(payload.length + 11).order(ByteOrder.LITTLE_ENDIAN);
    output.put((byte) 0x78);
    output.put((byte) 0x01);
    output.put((byte) 0x01);
    output.putShort((short) payload.length);
    output.putShort((short) ~payload.length);
    output.put(payload);
    Adler32 adler32 = new Adler32();
    adler32.update(payload);
    output.order(ByteOrder.BIG_ENDIAN).putInt((int) adler32.getValue());
    return output.array();
  }
}
