"""Fixture manifests remain stable when generator source text changes."""

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]


class FixtureGeneratorIdentityTests(unittest.TestCase):
    """Exercise the public generator commands with harmless source edits."""

    def test_python_manifests_ignore_generator_source_edits(self) -> None:
        """Keep fixture identities tied to generated bytes and procedure versions."""
        cases = (
            ("generate-ba2-fixtures.py", ()),
            ("generate-bsa-fixtures.py", ()),
            ("generate-bsa068-fixtures.py", ("generate-bsa-fixtures.py",)),
            ("generate-bsa069-fixtures.py", ("validate-bsa-wire.py",)),
        )
        for script_name, companions in cases:
            with self.subTest(script=script_name), tempfile.TemporaryDirectory() as temporary:
                work = Path(temporary)
                script = work / script_name
                shutil.copyfile(ROOT / "build" / script_name, script)
                for companion in companions:
                    shutil.copyfile(ROOT / "build" / companion, work / companion)
                first = work / "first"
                second = work / "second"
                subprocess.run(
                    [sys.executable, str(script), "--output", str(first)],
                    check=True,
                    capture_output=True,
                )
                script.write_text(script.read_text(encoding="utf-8") + "\n# editorial edit\n", encoding="utf-8")
                for companion in companions:
                    path = work / companion
                    path.write_text(path.read_text(encoding="utf-8") + "\n# editorial edit\n", encoding="utf-8")
                subprocess.run(
                    [sys.executable, str(script), "--output", str(second)],
                    check=True,
                    capture_output=True,
                )
                self.assertEqual(
                    (first / "manifest.json").read_bytes(),
                    (second / "manifest.json").read_bytes(),
                )

    def test_tes3_manifest_ignores_generator_source_edits(self) -> None:
        """Keep the PowerShell generator's manifest stable across editorial edits."""
        with tempfile.TemporaryDirectory() as temporary:
            work = Path(temporary)
            script = work / "generate-tes3-fixtures.ps1"
            shutil.copyfile(ROOT / "build/generate-tes3-fixtures.ps1", script)
            first = work / "first"
            second = work / "second"
            subprocess.run(
                ["pwsh", "-NoProfile", "-File", str(script), "-OutputDirectory", str(first)],
                check=True,
                capture_output=True,
            )
            script.write_text(script.read_text(encoding="utf-8") + "\n# editorial edit\n", encoding="utf-8")
            subprocess.run(
                ["pwsh", "-NoProfile", "-File", str(script), "-OutputDirectory", str(second)],
                check=True,
                capture_output=True,
            )
            self.assertEqual(
                (first / "manifest.json").read_bytes(),
                (second / "manifest.json").read_bytes(),
            )


if __name__ == "__main__":
    unittest.main()
